### ISSUE TITLE
Use BoxLayout instead of FloatLayout

### ISSUE THREAD

**Issue by chintal** [kivy-garden/frostedglass#3]
**Is your feature request related to a problem? Please describe.**

Just came across FrostedGlass today and assumed it would be trivially possible to put widgets into the FrostedLayout. I see, however, that FrostedLayout is (as of very recently) based on FloatLayout. I do feel bad for saying this right after #1 was closed.

The problem with using FloatLayout, from what I can tell : 
    - The FrostedGlass needs to be of a predetermined size or sized to fill available space. It's not easy to make it scale to fit the contents.
    - Children need to manually positioned / sized so that it can fit into the FrostedGlass

**Describe the solution you'd like**

If you were to base FrostedLayout on a BoxLayout, then children can be trivially added to the BoxLayout to build a complex layout which can also push out the size of the FloatLayout to contain the children. If you really did want a FloatLayout in some context, such a Layout can be added to the FrostedLayout(BoxLayout) and used as normally. It would also be possible to insert a  RelativeLayout inside the BoyLayout instead, to get a Float-like arrangement of children which remains confined to the area of the FrostedGlass

As an example, this is how I make BoxLayouts have colors:  

https://github.com/chintal/ebs-iot-linuxnode/blob/108eb20c67430c8b7d74b9dd75903304309e75c3/ebs/iot/linuxnode/widgets/colors.py#L77

**Comment by DexerBR** [comment]
Hi @chintal!
Considering that the `FrostedGlass`  widget tries to provide a standardized way to organize its children, changing its base class to `BoxLayout` would interfere with its own organization as the frosted glass effect is added to the `FrostedGlass` container as a child widget. Also, for non-adaptive uses, this would require most users to have to add a child layout like `FloatLayout` or `RelativeLayout` to `FrostedGlass`, just to avoid automatically arranging the BoxLayout-based `FrostedGlass` into columns and rows.

But nothing prevents you from binding the `size` of the child widget to the parent `size` (`FrostedGlass`) and getting the result you expect!
### Below is an example using `kvlang`, but you can also do this on the `python` side binding the sizes:

```kvlang
Image:
    id: background_image
    source: 'bg_example.png'
    size_hint: (1., 1.)
    allow_stretch: True
    pos_hint: {'center_x': 0.5,'center_y': 0.5}

FrostedGlass:
    id: fg
    background: background_image
    pos_hint: {'center_x': 0.5,'center_y': 0.5}
     size_hint: (None, None)
    blur_size: 20
    saturation: 1.2
    luminosity: 1.5
    overlay_color: "#76FF0300"
    noise_opacity: 0.12
    border_radius:  dp(10), dp(10), dp(10), dp(10)
    outline_color: "#76FF03"
    outline_width: 1

    BoxLayout:
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        size_hint: None, None
        size: self.minimum_size
        opacity: 0.65
        on_size:
            # 3 common ways to bind sizes
            fg.size = self.size #  bind to id
            self.parent.size = self.size  # bind to parent (exact size)
            self.parent.size = list(map(lambda x: x + dp(30), self.size))  # for extra spacing

        Button:
            size_hint: None, None
            size: 50, 100
        Button:
            size_hint: None, None
            size: 50, 200
        Button:
            size_hint: None, None
            size: 50, 300
        Button:
            size_hint: None, None
            size: 50, 100
```
### Result:
![image](https://user-images.githubusercontent.com/73297572/159733662-9850f674-6a34-4e30-8538-671689c07461.png)

**Comment by chintal** [comment]
@DexerBR Thanks. I see what you mean. Closing the issue. 

I'd still recommend including either a derived widget or at least an example in the docs which produces the more intuitive 'container'-type layout. The example you've posted here should be enough.

I realize that I've probably been overusing BoxLayout for some reason - probably because it's the first in the list of layouts - to create defined regions. You could use also consider using RelativeLayout instead. FloatLayout has the particular problem that it's not bound to anything in terms of it's position and size, and children need to be manually positioned all the time. Even positioning the FrostedGlass itself can get complicated if you want to position it within and relative to an existing complex layout. Yes, you can do the binding manually (and this is, admittedly, subjective), but it does take considerably more effort to get it right, with some of the bindings being in the 'reverse-to-typical' direction.
