### ISSUE TITLE
Cannot Remove A FrostedGlass widget

### ISSUE THREAD

**Issue by kengoon** [kivy-garden/frostedglass#9]
If you try to remove  a frosted glass widget using the `remove_widget`, the whole app crashes because on the `on_parent` method in `FrodtedGlass` class, the `self.parent` becomes None which makes `if parent.parent and parent != parent.parent:` on line `561` of frostedglass `__init__.py` to crash the application

a quick solution to that would be to do this:
```python
def on_parent(self, **args):
    if not self.parent:
        return
    ......................
    .....................
```

**Comment by DexerBR** [comment]
Fixed via #10
